#language: en
Feature: approval Info

  @fragment
  Scenario: selectAllSpecialPrograms
    * user is on the page "ApprovalInfoPage"
    * user selects in dropdown "Special Program" the value "None"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "COVID"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "DNR"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "CHF"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "SNP"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "REDD"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "Same Day Joints"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "FastTrack"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "ERAS"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "PED"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "Depression"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "TCP"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "MTCP"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "HTCP"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "Spine"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "Kidney"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "Heart"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "Lung"
    * user clicks the button "pageBody"
    * user selects in dropdown "Special Program" the value "Liver"
    * user clicks the button "pageBody"